export const sectionsData = [
  {
    name: "Pick Fruits",
    id: 1,
  },
  {
    name: "Select Quantity",
    id: 2,
  },
  {
    name: "Price Checkout",
    id: 3,
  },
];

const fruitsData = [
  {
    fruit: "Apple",
    id: "Apple-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/apple-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "1.31",
    total: "0.00",
  },
  {
    fruit: "Banana",
    id: "Banana-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/banana-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "1.50",
    total: "0.00",
  },
  {
    fruit: "Orange",
    id: "Orange-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/orange-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "1.00",
    total: "0.00",
  },
  {
    fruit: "Mango",
    id: "Mango-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/mango-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "4.00",
    total: "0.00",
  },
  {
    fruit: "Grapes",
    id: "Grapes-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/grapes-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "4.00",
    total: "0.00",
  },
  {
    fruit: "Pineapple",
    id: "Pineapple-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Pineapple-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "4.00",
    total: "0.00",
  },
  {
    fruit: "Pomegranate",
    id: "Pomegranate-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Pomegranate-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "3.00",
    total: "0.00",
  },
  {
    fruit: "Avocado",
    id: "Avocado-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Avocado-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "2.50",
    total: "0.00",
  },
  {
    fruit: "Coconut",
    id: "Coconut-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Coconut-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "2.00",
    total: "0.00",
  },
  {
    fruit: "Watermelon",
    id: "Watermelon-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Watermelon-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "3.00",
    total: "0.00",
  },
  {
    fruit: "Dragonfruit",
    id: "Dragonfruit-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/dragon.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "10.00",
    total: "0.00",
  },
  {
    fruit: "Strawberry",
    id: "Strawberry-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Strawberry-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "2.51",
    total: "0.00",
  },
  {
    fruit: "Blueberry",
    id: "Blueberry-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Blueberry-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "3.00",
    total: "0.00",
  },
  {
    fruit: "Blackberry",
    id: "Blackberry-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Blackberry-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "4.89",
    total: "0.00",
  },
  {
    fruit: "Gooseberry",
    id: "Gooseberry-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Gooseberry-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "4.99",
    total: "0.00",
  },
  {
    fruit: "Cherry",
    id: "Cherry-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Cherry-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "12.98",
    total: "0.00",
  },
  {
    fruit: "Apricot",
    id: "Apricot-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Apricot-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "3.00",
    total: "0.00",
  },
  {
    fruit: "Jackfruit",
    id: "Jackfruit-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/jackfruit-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "17.48",
    total: "0.00",
  },
  {
    fruit: "Kiwifruit",
    id: "Kiwifruit-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Kiwifruit-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "0.75",
    total: "0.00",
  },
  {
    fruit: "Lime",
    id: "Lime-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Lime-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "2.60",
    total: "0.00",
  },
  {
    fruit: "Peach",
    id: "Peach-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Peach-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "0.50",
    total: "0.00",
  },
  {
    fruit: "Pear",
    id: "Pear-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Pear-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "1.52",
    total: "0.00",
  },
  {
    fruit: "Tamarind",
    id: "Tamarind-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Tamarind-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "10.13",
    total: "0.00",
  },
  {
    fruit: "Custard-Apple",
    id: "Custard-Apple-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Custard-Apple-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "3.02",
    total: "0.00",
  },
  {
    fruit: "Fig",
    id: "Fig-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Fig-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "0.50",
    total: "0.00",
  },
  {
    fruit: "Guava",
    id: "Guava-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Guava-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "30.56",
    total: "0.00",
  },
  {
    fruit: "MuskMelon",
    id: "MuskMelon-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/MuskMelon-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "12.00",
    total: "0.00",
  },
  {
    fruit: "Olives",
    id: "Olives-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Olives-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "4.50",
    total: "0.00",
  },
  {
    fruit: "Java Plum",
    id: "Java-Plum-id",
    url: "https://i0.wp.com/onlymyenglish.com/wp-content/uploads/2020/11/Java-Plum-min.png?resize=150%2C150&ssl=1",
    selected: false,
    amount: 0,
    price: "31.74",
    total: "0.00",
  },
];

export default fruitsData;
